name: Security Scans

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'

      - name: Upload Semgrep Results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Run Grype Container Scan
        uses: anchore/grype-action@v1
        with:
          image: ghcr.io/${{ github.repository }}:latest

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image_ref: ghcr.io/${{ github.repository }}:latest

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks Secret Scan
        uses: zricethezav/gitleaks-action@v1

      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog-action@v3
